plugins {
    id "net.fabricmc.fabric-loom" version "${loom_version}"
}

repositories {
    def addGroup = { String url, String... groups ->
        exclusiveContent {
            forRepository {
                maven {
                    it.url = url
                }
            }
            filter {
                groups.each {
                    includeGroup it
                }
            }
        }
    }
    addGroup("https://maven.blamejared.com", "mezz.jei")
    addGroup("https://maven.cassian.cc", "cc.cassian.rrv")
    addGroup("https://maven.squiddev.cc", "cc.tweaked")
    addGroup("https://maven.nucleoid.xyz/releases", "eu.pb4")
    addGroup("https://api.modrinth.com/maven", "maven.modrinth")
}

version = "$project.mod_version-$project.mod_id"
group = project.maven_group

base {
    archivesName = "$project.archives_base_name-$project.minecraft_version"
}

loom {
    splitEnvironmentSourceSets()
    accessWidenerPath = file("src/main/resources/create.classtweaker")
    mods {
        create {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }
}

sourceSets {
    main {
        java {
            exclude 'com/zurrtum/create/compat/rei/**'
            exclude 'com/zurrtum/create/compat/eiv/**'
            exclude 'com/zurrtum/create/mixin/ArchitecturyMixin.java'
        }
    }
    client {
        java {
            exclude 'com/zurrtum/create/client/compat/rei/**'
            exclude 'com/zurrtum/create/client/compat/eiv/**'
            exclude 'com/zurrtum/create/client/mixin/CraftingViewRecipeAccessor.java'
            exclude 'com/zurrtum/create/client/mixin/FabricEIVMixin.java'
            exclude 'com/zurrtum/create/client/mixin/FluidItemSpecialRendererMixin.java'
            exclude 'com/zurrtum/create/client/mixin/ItemSlotMixin.java'
            exclude 'com/zurrtum/create/client/mixin/RecipeViewMenuMixin.java'
            exclude 'com/zurrtum/create/client/mixin/RecipeViewScreenMixin.java'
            exclude 'com/zurrtum/create/client/mixin/ViewTypeButtonMixin.java'
            exclude 'com/zurrtum/create/client/flywheel/lib/model/baked/DualVertexConsumer.java'
            exclude 'com/zurrtum/create/client/mixin/ItemFeatureRendererMixin.java'
            exclude 'com/zurrtum/create/client/mixin/ModelMixin.java'
            exclude 'com/zurrtum/create/client/mixin/ModelPartMixin.java'
        }
    }
}

tasks.register("serverJar", Jar) {
    archiveClassifier = "server"
    from sourceSets.main.output
    from("LICENSE")
    from("licenses") {
        into "licenses"
    }
}

tasks.build {
    dependsOn tasks.serverJar
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    if (project.compile_only_fabric_api.equals("true")) {
        compileOnly fabricApi.module("fabric-transfer-api-v1", project.fabric_version)
        compileOnly fabricApi.module("fabric-events-interaction-v0", project.fabric_version)
        compileOnly fabricApi.module("fabric-recipe-api-v1", project.fabric_version)
        compileOnly fabricApi.module("fabric-resource-loader-v1", project.fabric_version)
        compileOnly fabricApi.module("fabric-block-api-v1", project.fabric_version)
        compileOnly fabricApi.module("fabric-registry-sync-v0", project.fabric_version)
        clientCompileOnly fabricApi.module("fabric-renderer-api-v1", project.fabric_version)
        clientCompileOnly fabricApi.module("fabric-model-loading-api-v1", project.fabric_version)
    } else {
        implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
    }
//    modCompileOnly "me.shedaniel:RoughlyEnoughItems-fabric:${project.rei_version}"
//    if (project.compile_only_rei.equals("false")) {
//        modClientRuntimeOnly "me.shedaniel:RoughlyEnoughItems-fabric:${project.rei_version}"
//    }
    clientCompileOnly "mezz.jei:jei-${project.jei_version}"
//    modCompileOnly "maven.modrinth:eiv:${project.eiv_version}"
    clientCompileOnly "cc.cassian.rrv:reliable-recipe-viewer-fabric:${rrv_version}"
    compileOnly "cc.tweaked:cc-tweaked-${project.cct_version}"
    clientCompileOnly "eu.pb4:trinkets:${project.trinkets_version}"
    clientCompileOnly "maven.modrinth:sodium:${project.sodium_version}"
    clientCompileOnly "maven.modrinth:iris:${project.iris_version}"
}

processResources {
    def version = project.version
    inputs.property "version", version

    filesMatching("fabric.mod.json") {
        expand "version": version
    }

    exclude "_data"
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
}

java {
    withSourcesJar()
    tasks.named("sourcesJar", Jar) {
        from("LICENSE")
        from("licenses") {
            into "licenses"
        }
        exclude '_data'
        exclude 'assets'
        exclude 'data'
    }
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

jar {
    inputs.property "archivesName", project.base.archivesName

    from("LICENSE")
    from("licenses") {
        into "licenses"
    }
}
