# Done to increase the memory available to gradle.
org.gradle.jvmargs             = -Xmx4G
org.gradle.parallel            = true

org.gradle.configuration-cache = false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version              = 26.2
loader_version                 = 0.19.3
loom_version                   = 1.17-SNAPSHOT

# Fabric API (正式发布版)
compile_only_fabric_api        = true
fabric_version                 = 0.157.0+26.2

# Recipe Viewer
compile_only_rei               = true
rei_version                    = 20.0.811
jei_version                    = 26.2-fabric:29.6.2.34
eiv_version                    = 5.2.0+1.21.10
rrv_version                    = 8.3.1+26.2

# Sodium
sodium_version                 = mc26.2-0.8.12-fabric

# Iris
iris_version                   = 1.10.10+26.2-fabric

# CC: Tweaked
cct_version                    = 26.2-fabric:1.120.0

# Trinkets Updated
trinkets_version               = 4.1.0+26.2

# Mod Properties
mod_version                    = 6.0.10
mod_id                         = 1
maven_group                    = com.zurrtum
archives_base_name             = create-fly
